### PR TITLE
Update apps.json

### PR DESCRIPTION
**Pull request by jjeroch**
Updated the test data file as preparation of sprint 04

### CODE REVIEW

**Review by oyo — COMMENTED** [review]
what about the category? was that the `use_case`?

**Comment by jjeroch** [comment]
The use_case is the category ;)

**Review by oyo — APPROVED** [review]
passt :)

**Review by oyo — CHANGES_REQUESTED** [review]
sorry I approved that too early - can we please not use '_' in JSON attribute names?
Better call it `useCase` and `leadPicture` (we don't need app because we know the object is an app)

**Comment by jjeroch** [comment]
@oyo I wanted to keep the naming close to the DB naming, but totally fine for me if you prefer it without "app" and without "_"

**Comment by oyo** [comment]
@jjeroch ich habe das File schon mit meinem letzten PR aktualisiert, deshalb schließe ich deinen PR.

**Pull request closed without merging**
