### PR TITLE
Feature/cplp 714 edit bpn field

### PR DESCRIPTION
**Pull request by nidhigarg-bmw**

### CODE REVIEW

**Review by jjeroch — APPROVED** [review]
From what I can review, I am fine :)

**Review by oyo — CHANGES_REQUESTED** [review]
Hey Nidhi, yesterday I moved the company-portal to the new repository location. Can you please clone the project from the new repo at

https://github.com/catenax-ng/product-portal-frontend-registration

and apply the changes there to the file:

https://github.com/catenax-ng/product-portal-frontend-registration/blob/main/src/components/cax-companyData.tsx

From now on we should not work on the `tractusx-team-portal-onboarding/tractusx` repo any more.

**Comment by nidhigarg-bmw** [comment]
Hi Martin,

Okay will clone the new repo and do the changes

**Comment by ntruchsess** [comment]
@nidhigarg-bmw @oyo just to confirm: we close this PR here without merging as Nidhi is applying those changes to the new repo manually?

**Comment by nidhigarg-bmw** [comment]
Hi Nobert,

Are you talking about the PR which I created yesterday for old company-portal ? If yes then yes there is no need to merge I made the changes in new repo.

**Pull request merged**
