### PR TITLE
Feature/cax portal@cplp 596 email evaluations

### PR DESCRIPTION
**Pull request by fatihayyildiz**
Email template styles are improved
New html files for email templates are changed regarding with new styles

### CODE REVIEW

**Comment by jjeroch** [comment]
@fatihayyildiz if I understood Evelyn correctly, she moved the code to the new repo already. With that the whole commit is needed in CatenaX-NG. @evegufy is that assumption right?

**Comment by evegufy** [comment]
Yes, that's correct, I moved the backend yesterday in the new repo https://github.com/catenax-ng/product-portal-backend
@fatihayyildiz You'd need to create a PR against the new repo. I'll setup a quick call for Monday with you to sort this out. Sorry, for the inconvenience.

**Comment by fatihayyildiz** [comment]
@evegufy I moved changes already for new repo. But I need to keep this PR for tractusx-portal project changes. (for store static files). I tried to revert only backend related files but it didnt went well 😅 only some space and some Indentation changes remains same for my end. Can I just merge this PR ?

**Comment by evegufy** [comment]
@fatihayyildiz if you need the changes tractusx-portal project, it's fine for me to merge the PR.

**Review by evegufy — APPROVED** [review]

**Comment by fatihayyildiz** [comment]
Thanks @evegufy .  I will merge this PR

**Pull request merged**
